spring:
  rabbitmq:
    host: 39.107.57.188
    port: 61613
    username: guest
    password: guest
  config:
    import:
      - classpath:mbp-dev.yaml
      - classpath:security-dev.yaml
      - classpath:knife4j-dev.yaml
      - classpath:external.yaml
logging:
  level:
    com.baomidou.mybatisplus.mapper: DEBUG

z:
  # 生产环境要改为域名！！！
  domain: 192.168.0.102:18080
  domainUrl: http//${z.domain}