spring:
  rabbitmq:
    host: 39.107.57.188
    port: 61613
    username: guest
    password: guest
  config:
    import:
      - classpath:mbp-dev.yaml
      - classpath:security-dev.yaml
      - classpath:knife4j-dev.yaml
logging:
  level:
    com.baomidou.mybatisplus.mapper: DEBUG