spring:
  rabbitmq:
    host: 39.107.57.188
    port: 61613
    username: guest
    password: guest
  profiles:
    include: common
  config:
    import:
      - classpath:mbp-prod.yaml
      - classpath:security-prod.yaml
      - classpath:knife4j-prod.yaml
      - classpath:external.yaml
logging:
  level:
    com.baomidou.mybatisplus.mapper: DEBUG